name: No More Ravines
version: 0.2.1

pipeline:
  - src.plugins.canyon

meta:
  base_version: "1.21.9"

data_pack:
  load: src/datapack
  description: {"text":"No more Ravines\n1.21.9 - 26.1", "color":"gray"}
  min_format: 82
  max_format: 101

output: build